channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - setuptools<58
  - altair=4.2.2
  - tabulate=0.9.0
  - matplotlib=3.7.1
  - numpy=1.22.4
  - openpyxl=3.1.2
  - pip
  - pip:
    - git+https://github.com/camriddell/dolark.py
