on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: build conda environments
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: binder/environment.yml
          environment-name: test-build
          cache-env: true

