on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: build conda environments
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: binder/environment.yml
          environment-name: test-build
          cache-env: true

  build-repo2docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: 'true'

  log-results:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-conda, build-repo2docker]
    steps:
      - uses: actions/checkout@v3
      - run: echo 'hi'
      # - name: Get job statuses
      #   id: get_status
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     statuses=""
      #     for job in job1 job2 job3; do
      #       status=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      #         https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs \
      #         | jq -r --arg job_name "$job" '.jobs[] | select(.name==$job_name) | .conclusion')
      #       statuses="$statuses $job:$status"
      #     done
      #     echo "::set-output name=statuses::$statuses"
      # - name: Display job statuses
      #   run: echo "Job Statuses: ${{ steps.get_status.outputs.statuses }}"
